apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-135108-tmtm-service
spec:
  selector:
    app: enterprise-system-135108-tmtm
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
